### ISSUE TITLE
Initial work

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#1]
Do something

**Comment by DronMDF** [comment]
@0crat hello

**Comment by 0crat** [comment]
I'm not managing this GitHub repository (dronmdf/telebot). You have to contact me in Slack first.

**Comment by DronMDF** [comment]
@0crat  hello

**Comment by DronMDF** [comment]
@0crat  in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/1#issuecomment-321579380))

@DronMDF Job `gh:dronmdf/telebot#1` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+15](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#1` assigned to @spark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/1#issuecomment-326405184))

@DronMDF @spark resigned from `gh:dronmdf/telebot#1`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#1` assigned to @spark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by roman901** [comment]
@0crat refuse

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by roman901** [comment]
@0crat refuse

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by roman901** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/1#issuecomment-326663692))

@roman901 Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "roman901").

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/1#issuecomment-330657126))

@DronMDF Job `gh:dronmdf/telebot#1` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @spark, total is [+90](http://www.0crat.com/u/spark).

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#1` was not in scope
