### ISSUE TITLE
Взаимодействие с сервером telegram

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#10]

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/10#issuecomment-330656552))

@DronMDF Job `gh:dronmdf/telebot#10` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+150](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#10` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Нужно написать небольшой документик,
Где кратко описать - как получить сообщения с сервера. url, формат запроса, формат ответа.
То же самое - как послать сообщение.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/10#issuecomment-337152735))

@DronMDF Job `gh:dronmdf/telebot#10` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+475](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#10` is now out of scope.
