### ISSUE TITLE
Список анализируемой информации

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#11]
Необходимо описать это в отдельном md файле.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/11#issuecomment-330656616))

@DronMDF Job `gh:dronmdf/telebot#11` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+165](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#11` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/11#issuecomment-333282384))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#11`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#11` assigned to @talykovnikita, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/11#issuecomment-333308953))

@DronMDF @talykovnikita resigned from `gh:dronmdf/telebot#11`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#11` assigned to @drakonda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/11#issuecomment-333309558))

@DronMDF @drakonda resigned from `gh:dronmdf/telebot#11`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#11` assigned to @kirill125, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Нужно написать md файлик... что-то типа прообраза докумментации. (Может быть FEATURES.md)
Где написать буквально несколько строк о том, какие у нас есть варианты в плане анализа.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/11#issuecomment-337162006))

@DronMDF Job `gh:dronmdf/telebot#11` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+470](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#11` is now out of scope.

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+600](http://www.0crat.com/u/dronmdf).
