### ISSUE TITLE
Интеграция с codecov

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#12]
Может быть реализована после #9

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/12#issuecomment-330656770))

@DronMDF Job `gh:dronmdf/telebot#12` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+180](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#12` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/12#issuecomment-333311009))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#12`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#12` assigned to @kirill125, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/12#issuecomment-333311223))

@DronMDF @kirill125 resigned from `gh:dronmdf/telebot#12`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#12` assigned to @alexandersamrega, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Это наверное самое сложное, потому, что не хватает фундамента.
вообще это надо встроить в скрипт юниттестирования, который заодно соберет coverage информацию. Которую потом можно будет залить на сервер codecov и это даст дополнительные метрики для проекта.

Но пока можно упростить эту задачу до того, чтобы создать в корне проекта конфигурацию для codecov. (можешь подсмотреть в github.com/DronMDF/goost)

**Comment by asamrega** [comment]
Здравствуйте!

Хотел Вас предупредить, что у меня не получится, к сожалению, выполнять задания, поскольку не хватает времени.

Уведомляю Вас, чтобы оно не висело без дела.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/12#issuecomment-335710866))

@DronMDF Job `gh:dronmdf/telebot#12` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+435](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#12` is now out of scope.
