### ISSUE TITLE
Список команд бота

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#13]
Нужно создать файл md, в котором будет хранится описание команд.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/13#issuecomment-330657790))

@DronMDF Job `gh:dronmdf/telebot#13` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+195](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#13` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat  refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/13#issuecomment-333312975))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#13`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#13` assigned to @chniks, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Здесь нужно создать файл (возможно USAGE.md)
После этого поставить себя на место администратора.
И подумать что ты хотел бы спросить у сервера?
Опиши это в файлике.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#13` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @chniks, total is [+45](http://www.0crat.com/u/chniks).
