### ISSUE TITLE
Распарсить xml вывод radon tools

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#16]
Необходимо, чтобы в случае превышения complexity скрипт завершался с кодом возврата  не ноль.
Вызывать его будет удобно через pipe.
radare -cc -xml | script

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/16#issuecomment-333574057))

@DronMDF Job `gh:dronmdf/telebot#16` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+270](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#16` assigned to @olejka, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Хотя эту задачу я поставил слишком конкретно.
Основная цель - мне нужно чтобы при определенных значениях complexity происходил выход по ошибке. Возможно radon умеет это и без посторонней помощи?

**Comment by DronMDF** [comment]
Я принял PR, значит задача закрыта.
Хотя по хорошему - тебе стоило превратить непонимание в новые задачи.
Но не все сразу. :)

**Comment by DronMDF** [comment]
@0crat Где деньги? Я не понял.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#16` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @olejka, total is [+75](http://www.0crat.com/u/olejka).

**Comment by DronMDF** [comment]
@0crat То-то же.. :)

**Comment by 0crat** [comment]
> @0crat Где деньги? Я не понял. ([here](https://github.com/DronMDF/telebot/issues/16#issuecomment-335082616))

@DronMDF Can't understand "Где", try one of these:
  * `assign` Assign a performer to this issue
  * `hello` Just say hello
  * `in` Register this issue in scope (WBS)
  * `out` Remove this issue from scope (WBS)
  * `resign` Resign from this issue
  * `version` Print current version of the bot

**Comment by 0crat** [comment]
> @0crat То-то же.. :) ([here](https://github.com/DronMDF/telebot/issues/16#issuecomment-335083545))

@DronMDF Can't understand "То-то", try one of these:
  * `assign` Assign a performer to this issue
  * `hello` Just say hello
  * `in` Register this issue in scope (WBS)
  * `out` Remove this issue from scope (WBS)
  * `resign` Resign from this issue
  * `version` Print current version of the bot
