### ISSUE TITLE
Скрипт для проверки стиля.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#17]
Должен изнутри  запускать pep8 на все файлы в репозитории.
Если pep8 находит ошибки - скрипт должен возвращать код возврата отличный от 0.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/17#issuecomment-333629099))

@DronMDF Job `gh:dronmdf/telebot#17` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+285](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#17` assigned to @makar93, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/17#issuecomment-337151510))

@DronMDF Job `gh:dronmdf/telebot#17` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+480](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#17` is now out of scope.
