### ISSUE TITLE
Скрипт для юниттестирования.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#18]
В питоновском модуле unittest если test discovery.
Для того чтобы он обнаружил все тесты - нужно запускать его со специальными параметрами.
Чтобы эти параметры не запоминать - нужен скрипт, который будет содержать все это внутри.
В случае нарушения тестов - скрипт должен вернуть код возврата отличный от 0

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/18#issuecomment-333630022))

@DronMDF Job `gh:dronmdf/telebot#18` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+300](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#18` assigned to @makar93, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@Makar93 Ну вот, теперь у тебя сразу три задачи. :)
@0crat refuse

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/18#issuecomment-333640410))

@DronMDF @makar93 resigned from `gh:dronmdf/telebot#18`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#18` assigned to @invisea, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by IlyaMakarov93** [comment]
Здравствуйте, Андрей!

Спасибо Вам за задачи, до понедельника постараюсь их сделать :) 

С уважением к Вам и Вашему делу, Илья Макаров.

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/18#issuecomment-337150592))

@DronMDF Job `gh:dronmdf/telebot#18` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+485](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#18` is now out of scope.
