### ISSUE TITLE
Необходима инструкция по установке сервера

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#19]
INSTALL.md

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/19#issuecomment-333632158))

@DronMDF Job `gh:dronmdf/telebot#19` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+315](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#19` assigned to @makar93, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/19#issuecomment-333639813))

@DronMDF @makar93 resigned from `gh:dronmdf/telebot#19`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#19` assigned to @invisea, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/19#issuecomment-333658025))

@DronMDF @invisea resigned from `gh:dronmdf/telebot#19`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#19` assigned to @hayfay, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/19#issuecomment-333659984))

@DronMDF @hayfay resigned from `gh:dronmdf/telebot#19`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#19` assigned to @barbaragrape, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#19` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @barbaragrape, total is [+30](http://www.0crat.com/u/barbaragrape).
