### ISSUE TITLE
Найти web-приложение, которое интересно мониторить.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#20]
Для тестовой эксплуатации будет развернут сервер (VDS)
На котором можно будет поднять что нибудь LAMPовое...
Типа honeypot, куда будет установле сервер для наблюдения.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/20#issuecomment-333638446))

@DronMDF Job `gh:dronmdf/telebot#20` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+330](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#20` assigned to @invisea, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/20#issuecomment-333655159))

@DronMDF @invisea resigned from `gh:dronmdf/telebot#20`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#20` assigned to @hayfay, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/20#issuecomment-337226179))

@DronMDF Job `gh:dronmdf/telebot#20` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+585](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#20` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+615](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:dronmdf/telebot#20`.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#20` was not in scope
