### ISSUE TITLE
Написать источник событий (размер диска)

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#21]
Интерфейс следующий:

```python
class ...:
    def events(self):
          """ Должен вернуть массив из одного события, в котором содержится размер диска """ 
```

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/21#issuecomment-333846107))

@DronMDF Job `gh:dronmdf/telebot#21` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+345](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#21` assigned to @1640max, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#21` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @1640max, total is [+30](http://www.0crat.com/u/1640max).
