### ISSUE TITLE
Написать источник событий (Время работы системы)

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#22]
Интерфейс следующий:

```python
class ...:
    def events(self):
          """ Должен вернуть массив из одного события, в котором содержится время с момента запуска системы """ 
```

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/22#issuecomment-333853932))

@DronMDF Job `gh:dronmdf/telebot#22` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+360](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#22` assigned to @meladark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#22` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @meladark, total is [+30](http://www.0crat.com/u/meladark).
