### ISSUE TITLE
Написать источник событий (syslog)

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#23]
Интерфейс следующий:

```python
class ...:
    def events(self):
          """ Должен вернуть массив событий, которые возникли с момента последнего запуска """ 
```

Глубоко зарываться не надо, можно ограничиться заглушкой.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/23#issuecomment-333859577))

@DronMDF Job `gh:dronmdf/telebot#23` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+375](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#23` assigned to @ruslangv, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/23#issuecomment-336983849))

@DronMDF Job `gh:dronmdf/telebot#23` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+460](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/23#issuecomment-336984436))

@DronMDF Oops! There is an open order for this job, @dronmdf is still working with it.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#23` is now out of scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:dronmdf/telebot#23`.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#23` was not in scope

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").
