### ISSUE TITLE
Написать источник событий (Загрузка CPU)

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#24]
Интерфейс следующий:

```python
class ...:
    def events(self):
          """ Должен вернуть массив из одного события, в котором содержится уровень загрузки CPU за последнюю минуту. """ 
```

Глубоко зарываться не надо, можно ограничиться заглушкой.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/24#issuecomment-333865924))

@DronMDF Job `gh:dronmdf/telebot#24` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+390](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#24` assigned to @yuran8shon, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#24` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yuran8shon, total is [+45](http://www.0crat.com/u/yuran8shon).
