### ISSUE TITLE
Next new work

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#3]

**Comment by DronMDF** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/DronMDF/telebot/issues/3#issuecomment-321543104))

@DronMDF Hey, what's up, how is it going?

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/3#issuecomment-321763896))

@DronMDF Job `gh:dronmdf/telebot#3` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+45](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#3` assigned to @spark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @tanika95

**Comment by 0crat** [comment]
> @0crat assign @tanika95 ([here](https://github.com/DronMDF/telebot/issues/3#issuecomment-322899790))

@DronMDF Job `gh:dronmdf/telebot#3` assigned to @tanika95, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)). @tanika95 is not a member of this project yet, but can request to join. @tanika95 check your [Zerocracy profile](http://www.0crat.com/u/tanika95) and follow the instructions.

**Comment by DronMDF** [comment]
@0crat assign @tanyaerm

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#3` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @tanika95, total is [+45](http://www.0crat.com/u/tanika95).
