### ISSUE TITLE
config.py:6-9: А давайте пока для простоты передадим...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#36]
The puzzle `35-88e76001` (from #35) in [`tb/config.py`](https://github.com/DronMDF/telebot/blob/master/tb/config.py) (lines 6-9) has to be resolved: "А давайте пока для простоты передадим токен в параметрах командной строки, пусть будет первым параметром но запрос нужно делать по ключу. Ключ для токена будет 'telegram.token' А список аргументов командной строки содержится в self.args"

The puzzle was created by Andrey Valyaev on 09-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/36#issuecomment-335353697))

@DronMDF Job `gh:dronmdf/telebot#36` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#36` assigned to @olejka, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @meladark

**Comment by 0crat** [comment]
> @0crat assign @meladark  ([here](https://github.com/DronMDF/telebot/issues/36#issuecomment-338700122))

@DronMDF Job `gh:dronmdf/telebot#36` assigned to @meladark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+650](http://www.0crat.com/u/dronmdf).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/36#issuecomment-339319061))

@DronMDF Job `gh:dronmdf/telebot#36` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+635](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0pdd** [comment]
The puzzle `35-88e76001` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#36` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+660](http://www.0crat.com/u/dronmdf).
