### ISSUE TITLE
telegram.py:7-11: Нужно обратиться к серверу telegram и...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#37]
The puzzle `35-519019b8` (from #35) in [`tb/sources/telegram.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/telegram.py) (lines 7-11) has to be resolved: "Нужно обратиться к серверу telegram и вытащить оттуда свежие сообщения. Для этого нужно использовать https://python-telegram-bot.org/ Но пример неправильный, поскольку нам нужно только забрать сообщения с сервера. Что-то типа этого: telegram.Bot.getUpdates"

The puzzle was created by Andrey Valyaev on 09-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/37#issuecomment-335373583))

@DronMDF Job `gh:dronmdf/telebot#37` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#37` assigned to @barbaragrape, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @sminux

**Comment by 0crat** [comment]
> @0crat assign @sminux  ([here](https://github.com/DronMDF/telebot/issues/37#issuecomment-338754851))

@DronMDF Job `gh:dronmdf/telebot#37` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+640](http://www.0crat.com/u/dronmdf).

**Comment by 0pdd** [comment]
The puzzle `35-519019b8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#37` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+120](http://www.0crat.com/u/sminux).
