### ISSUE TITLE
application.py:12-14: Реализовать в Application.run()...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#38]
The puzzle `35-d7be7cdc` (from #35) in [`tb/application.py`](https://github.com/DronMDF/telebot/blob/master/tb/application.py) (lines 12-14) has to be resolved: "Реализовать в Application.run() основной цикл приложения Этот цикл должен вытягивать события из self.source и отправлять в self.storage, Интерфейсы описаны в файле types.py, нарушать нельзя."

The puzzle was created by Andrey Valyaev on 09-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by DronMDF** [comment]
Интерфейсы описаны в файле TYPES.md, потому что тянуть их в модули оказалось достаточно сложно. циклические зависимости по модулям. Поэтому я их просто описал.

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/38#issuecomment-335273179))

@DronMDF Job `gh:dronmdf/telebot#38` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#38` assigned to @pavelonex, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @yuran8shon

**Comment by 0crat** [comment]
> @0crat assign @yuran8shon  ([here](https://github.com/DronMDF/telebot/issues/38#issuecomment-338754707))

@DronMDF Job `gh:dronmdf/telebot#38` assigned to @yuran8shon, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+645](http://www.0crat.com/u/dronmdf).

**Comment by 0pdd** [comment]
The puzzle `35-d7be7cdc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalStateException: event of type 'closed' not found in issue #38
	at com.jcabi.github.Issue$Smart.latestEvent_aroundBody40(Issue.java:365)
	at com.jcabi.github.Issue$Smart$AjcClosure41.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.latestEvent(Issue.java:354)
	at com.zerocracy.radars.github.RbVerifyCloser.closer(RbVerifyCloser.java:83)
	at com.zerocracy.radars.github.RbVerifyCloser.react(RbVerifyCloser.java:47)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Re... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by DronMDF** [comment]
@yegor256 Что-то эта штука никак не работает. :)

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#38` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yuran8shon, total is [+75](http://www.0crat.com/u/yuran8shon).

**Comment by yegor256** [comment]
@DronMDF это "баг" в GitHub API. Он присылает нам webhook о том, что тикет закрылся. Мы пытаемся к этому тикету тут же обратиться, а сообщения о закрытии там еще нет. И мы получаем ошибку. Уже исправили. Теперь будем делать несколько попыток, пока тикет не обновится в GitHub API.
