### ISSUE TITLE
telegram.py:6-10: Нужно обратиться к серверу telegram и...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#39]
The puzzle `35-fca646b9` (from #35) in [`tb/storage/telegram.py`](https://github.com/DronMDF/telebot/blob/master/tb/storage/telegram.py) (lines 6-10) has to be resolved: "Нужно обратиться к серверу telegram и залить туда. Для этого нужно использовать https://python-telegram-bot.org/ Но пример неправильный, поскольку нам нужно только отправить сообщения на сервер. что-то типа этого: telegram.Bot.sendMessage"

The puzzle was created by Andrey Valyaev on 09-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/39#issuecomment-335380276))

@DronMDF Job `gh:dronmdf/telebot#39` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#39` assigned to @1640max, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/39#issuecomment-339319132))

@DronMDF Job `gh:dronmdf/telebot#39` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+630](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0pdd** [comment]
The puzzle `35-fca646b9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#39` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+690](http://www.0crat.com/u/dronmdf).
