### ISSUE TITLE
hdd.py:3-4: Необходимо определить размер...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#41]
The puzzle `40-c7c972e3` (from #40) in [`tb/sources/hdd.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/hdd.py) (lines 3-4) has to be resolved: "Необходимо определить размер свободного места на диске. Если размер свободного места меньше чем 10% от диска - сгенерировать событие."

The puzzle was created by Andrey Valyaev on 10-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/41#issuecomment-335441523))

@DronMDF Job `gh:dronmdf/telebot#41` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#41` assigned to @meladark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@meladark this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@meladark resigned from `gh:dronmdf/telebot#41`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#41` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#41` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#41` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#41` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/41#issuecomment-346138567))

@DronMDF @dronmdf resigned from `gh:dronmdf/telebot#41`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/41#issuecomment-346138567))

@DronMDF Job `gh:dronmdf/telebot#41` is now out of scope.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/41#issuecomment-346138567))

@DronMDF Oops! Job `gh:dronmdf/telebot#41` is not in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:dronmdf/telebot#41`.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#41` is not in scope.
