### ISSUE TITLE
syslog.py:3-5: Необходимо получить список событий,...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#43]
The puzzle `40-b7de133b` (from #40) in [`tb/sources/syslog.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/syslog.py) (lines 3-5) has to be resolved: "Необходимо получить список событий, которые возникли с момента последнего обращения. Не знаю точно, что мы хотим там увидеть, Давайте для начала найдет все события от systemd и вернем их в виде событий."

The puzzle was created by Andrey Valyaev on 10-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/43#issuecomment-335577515))

@DronMDF Job `gh:dronmdf/telebot#43` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#43` assigned to @ruslangv, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @sminux

**Comment by 0crat** [comment]
> @0crat assign @sminux ([here](https://github.com/DronMDF/telebot/issues/43#issuecomment-336845832))

@DronMDF Job `gh:dronmdf/telebot#43` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@sminux Вот например есть такой топик, в котором они парсят формат сислога.
https://stackoverflow.com/questions/41137742/syslog-parsing-using-pyparsing
Можно тупо скопипастить.

**Comment by 0pdd** [comment]
The puzzle `40-b7de133b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#43` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+120](http://www.0crat.com/u/sminux).
