### ISSUE TITLE
.travis.yml:8-8: Интегрировать test в setup.py

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#45]
The puzzle `12-df202e49` (from #12) in [`.travis.yml`](https://github.com/DronMDF/telebot/blob/master/.travis.yml) (lines 8-8) has to be resolved: "Интегрировать test в setup.py"

The puzzle was created by Andrey Valyaev on 11-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `12-df202e49` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#45` was not in scope
