### ISSUE TITLE
utility.py:6-7: Необходимо собрать actions со всех...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#48]
The puzzle `47-cef35592` (from #47) in [`tb/sources/utility.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/utility.py) (lines 6-7) has to be resolved: "Необходимо собрать actions со всех внутренних источников и вернуть в виде общего списка"

The puzzle was created by Andrey Valyaev on 13-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/48#issuecomment-336401045))

@DronMDF Job `gh:dronmdf/telebot#48` is in scope.

**Comment by DronMDF** [comment]
@yegor256 0crat was not elected this job. Why?
Next job too... i need help.

**Comment by yegor256** [comment]
@DronMDF should make the election in the next few hours. I'll keep an eye on this task.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#48` assigned to @chniks, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@yegor256 Thank's

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/48#issuecomment-341881158))

@DronMDF @chniks resigned from `gh:dronmdf/telebot#48`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/48#issuecomment-341881158))

@DronMDF Job `gh:dronmdf/telebot#48` is now out of scope.

**Comment by DronMDF** [comment]
@0crat assign @sminux

**Comment by 0crat** [comment]
> @0crat assign @sminux  ([here](https://github.com/DronMDF/telebot/issues/48#issuecomment-346139827))

@DronMDF Job `gh:dronmdf/telebot#48` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+770](http://www.0crat.com/u/dronmdf).

**Comment by 0pdd** [comment]
The puzzle `47-cef35592` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#48` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+240](http://www.0crat.com/u/sminux).
