### ISSUE TITLE
utility.py:6-7: Необходимо пробросить action во все...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#49]
The puzzle `47-b5b1bd9d` (from #47) in [`tb/storage/utility.py`](https://github.com/DronMDF/telebot/blob/master/tb/storage/utility.py) (lines 6-7) has to be resolved: "Необходимо пробросить action во все вложенные storage"

The puzzle was created by Andrey Valyaev on 13-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/49#issuecomment-336401104))

@DronMDF Job `gh:dronmdf/telebot#49` is in scope.

**Comment by DronMDF** [comment]
@0crat assign @yuran8shon

**Comment by 0crat** [comment]
> @0crat assign @yuran8shon  ([here](https://github.com/DronMDF/telebot/issues/49#issuecomment-336548078))

@DronMDF Job `gh:dronmdf/telebot#49` assigned to @yuran8shon, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @sminux

**Comment by 0crat** [comment]
> @0crat assign @sminux  ([here](https://github.com/DronMDF/telebot/issues/49#issuecomment-340555345))

@DronMDF Job `gh:dronmdf/telebot#49` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
> @0crat assign @sminux  ([here](https://github.com/DronMDF/telebot/issues/49#issuecomment-340555345))

@DronMDF Oops! Job `gh:dronmdf/telebot#49` is already assigned to @sminux, sorry.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+685](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+685](http://www.0crat.com/u/dronmdf).

**Comment by 0pdd** [comment]
The puzzle `47-b5b1bd9d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#49` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+150](http://www.0crat.com/u/sminux).
