### ISSUE TITLE
Добавить pylint

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#51]
>>> from pylint.lint import PyLinter
>>> l = PyLinter()
>>> l.load_default_plugins()
>>> l.check('setup.py')

Надо только разобраться, как поотключать у него все лишнее.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/51#issuecomment-337845114))

@DronMDF Job `gh:dronmdf/telebot#51` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+615](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#51` assigned to @1640max, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/51#issuecomment-337852820))

@DronMDF Oops! There is an open order for this job, @1640max is still working with it.

**Comment by DronMDF** [comment]
@yegor256 I can not give a command 'out' on the assigned task.
@1640max Не обращай внимания на эту задачу, это эксперименты.

**Comment by yegor256** [comment]
@DronMDF yes, you have to cancel the order first. Use `reject`.

**Comment by DronMDF** [comment]
@0crat how to reject order?

**Comment by 0crat** [comment]
> @0crat how to reject order? ([here](https://github.com/DronMDF/telebot/issues/51#issuecomment-337894920))

@DronMDF Can't understand "how", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `version` Print current version of the bot

**Comment by DronMDF** [comment]
@yegor256 How to make reject? Did you mean 'refuse'?
refuse not in help by the way.

**Comment by DronMDF** [comment]
@0crat reject

**Comment by 0crat** [comment]
> @0crat reject ([here](https://github.com/DronMDF/telebot/issues/51#issuecomment-337895893))

@DronMDF Oops! The job `gh:dronmdf/telebot#51` is assigned to @1640max, you @dronmdf cannot resign, since you are not a PO or ARC.

**Comment by DronMDF** [comment]
@yegor256 reject is synonym of refuse? Doesn't work for me.
This is not what I want. I do not want to assign a job to someone else. I want to remove it.

**Comment by yegor256** [comment]
@DronMDF I guess you're right, `out` should stop the working order too. It's fixed. Try to `out` again.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/51#issuecomment-337926412))

@DronMDF @1640max resigned from `gh:dronmdf/telebot#51`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/51#issuecomment-337926412))

@DronMDF Job `gh:dronmdf/telebot#51` is now out of scope.

**Comment by DronMDF** [comment]
@yegor256 Thank's. This is logical.

**Comment by DronMDF** [comment]
Че-то мне как-то расхотелось прикручивать pylint. Он совершенно не умеет держать язык за зубами (работать и не писать ничего на экран). Кроме того совершенно не ООП. Просто ужас, какой плоский код.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:dronmdf/telebot#51`.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#51` is not in scope.

**Comment by DronMDF** [comment]
А может быть не прикручивать а запускать просто так?

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#51` was not in scope
