### ISSUE TITLE
telegram.py:4-4: Перенести AcMessage в правильное место

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#55]
The puzzle `39-83038aa7` (from #39) in [`tb/sources/telegram.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/telegram.py) (lines 4-4) has to be resolved: "Перенести AcMessage в правильное место"

The puzzle was created by Andrey Valyaev on 25-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `39-83038aa7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:dronmdf/telebot#55`.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#55` is not in scope.
