### ISSUE TITLE
telegram.py:18-21: Необходимо сохранить в БД номер...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#56]
The puzzle `39-f74a6074` (from #39) in [`tb/storage/telegram.py`](https://github.com/DronMDF/telebot/blob/master/tb/storage/telegram.py) (lines 18-21) has to be resolved: "Необходимо сохранить в БД номер сообщения, с которым работал бот. Это необходимо для того, чтобы после перезапуска бот не повторял свои сообщения. Можно использовать https://pypi.python.org/pypi/tinydb - достаточно простая штука."

The puzzle was created by Andrey Valyaev on 29-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/56#issuecomment-340427007))

@DronMDF Job `gh:dronmdf/telebot#56` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#56` assigned to @1640max, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@1640max this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@1640max resigned from `gh:dronmdf/telebot#56`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#56` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#56` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#56` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#56` is not assigned to anyone.

**Comment by 0pdd** [comment]
The puzzle `39-f74a6074` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#56` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+210](http://www.0crat.com/u/sminux).
