### ISSUE TITLE
telegram.py:22-23: Нужно восстановить из БД значние...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#57]
The puzzle `39-e0443908` (from #39) in [`tb/sources/telegram.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/telegram.py) (lines 22-23) has to be resolved: "Нужно восстановить из БД значние счетчика и использовать его для последующих операций."

The puzzle was created by Andrey Valyaev on 29-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/57#issuecomment-340427071))

@DronMDF Job `gh:dronmdf/telebot#57` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#57` assigned to @drakonda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@drakonda this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@drakonda resigned from `gh:dronmdf/telebot#57`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#57` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#57` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#57` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#57` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/57#issuecomment-346139184))

@DronMDF Job `gh:dronmdf/telebot#57` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+775](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0pdd** [comment]
The puzzle `39-e0443908` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#57` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+800](http://www.0crat.com/u/dronmdf).
