### ISSUE TITLE
utility.py:16-18: В процессе выполнения action может...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#58]
The puzzle `39-b97bcefa` (from #39) in [`tb/sources/utility.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/utility.py) (lines 16-18) has to be resolved: "В процессе выполнения action может возникнуть исключение. В этом случае необходимо донести до админитратора информацию о том, что пошло не так."

The puzzle was created by Andrey Valyaev on 29-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/58#issuecomment-340294245))

@DronMDF Job `gh:dronmdf/telebot#58` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#58` assigned to @1640max, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@1640max this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0pdd** [comment]
The puzzle `39-b97bcefa` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@1640max resigned from `gh:dronmdf/telebot#58`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#58` is not assigned to anyone.
