### ISSUE TITLE
config.py:2-4: Необходимо организовать чтение...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#59]
The puzzle `39-ad668363` (from #39) in [`tb/config.py`](https://github.com/DronMDF/telebot/blob/master/tb/config.py) (lines 2-4) has to be resolved: "Необходимо организовать чтение конфигурации из файла конфигурации. Формат файла конфигурации - ini модуль: https://docs.python.org/3/library/configparser.html"

The puzzle was created by Andrey Valyaev on 29-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/59#issuecomment-340294282))

@DronMDF Job `gh:dronmdf/telebot#59` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#59` assigned to @meladark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/59#issuecomment-341055081))

@DronMDF Job `gh:dronmdf/telebot#59` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#59` is already assigned to @dronmdf, sorry.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+680](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by DronMDF** [comment]
@yegor256 Last message is strange... 0crat does not have a role in the project. This is a fact.

**Comment by yegor256** [comment]
@DronMDF yeah, it's a bug, will fix it today, sorry)

**Comment by 0pdd** [comment]
The puzzle `39-ad668363` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#59` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+775](http://www.0crat.com/u/dronmdf).
