### ISSUE TITLE
Реализация базы на основе tinydb 

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#63]

**Comment by DronMDF** [comment]
@0crat in

**Comment by DronMDF** [comment]
@0crat assign @sminux

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/63#issuecomment-340554424))

@DronMDF Job `gh:dronmdf/telebot#63` is in scope.

**Comment by 0crat** [comment]
> @0crat assign @sminux  ([here](https://github.com/DronMDF/telebot/issues/63#issuecomment-340554479))

@DronMDF Job `gh:dronmdf/telebot#63` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+700](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+695](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#63` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+180](http://www.0crat.com/u/sminux).
