### ISSUE TITLE
Скрипт для запуска сервиса

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#67]
https://stackoverflow.com/questions/4705564/python-script-as-linux-service-daemon

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#67` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+685](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+685](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#67` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+715](http://www.0crat.com/u/dronmdf).
