### ISSUE TITLE
reaction.py:19-21: Нужно сделать такую реакцию, которая...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#74]
The puzzle `68-ff971afd` (from #68) in [`tb/sources/reaction.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/reaction.py) (lines 19-21) has to be resolved: "Нужно сделать такую реакцию, которая могла бы выбирать из нескольких реакций. То есть необходимо реализовать ReactionChoiced"

The puzzle was created by Andrey Valyaev on 20-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/74#issuecomment-345811589))

@DronMDF Job `gh:dronmdf/telebot#74` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#74` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat assign @Michaelo0

**Comment by 0crat** [comment]
> @0crat assign @Michaelo0 ([here](https://github.com/DronMDF/telebot/issues/74#issuecomment-346139647))

@DronMDF Job `gh:dronmdf/telebot#74` assigned to @michaelo0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+770](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
@michaelo0 this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0pdd** [comment]
The puzzle `68-ff971afd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#74` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @michaelo0, total is [+30](http://www.0crat.com/u/michaelo0).
