### ISSUE TITLE
setup.py для разворачивания приложения

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#8]

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/8#issuecomment-330656258))

@DronMDF Job `gh:dronmdf/telebot#8` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+120](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#8` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/8#issuecomment-333236755))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#8`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#8` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/8#issuecomment-333308789))

@DronMDF @sminux resigned from `gh:dronmdf/telebot#8`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#8` assigned to @drakonda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Поясню, Содержимое скрипта не так важно,
Так что можно взять из докумментации и скопировать.
Поскольку у нас пока нет кода - мы всеравно не будем его запускать.
Все сложности устраним позже.

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/8#issuecomment-335576984))

@DronMDF Job `gh:dronmdf/telebot#8` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+415](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#8` is now out of scope.
