### ISSUE TITLE
hdd.py:7-8: Сформировать Action, который доставит...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#81]
The puzzle `41-96ac84d5` (from #41) in [`tb/sources/hdd.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/hdd.py) (lines 7-8) has to be resolved: "Сформировать Action, который доставит админу уведомление о том, что на диске кончилось место"

The puzzle was created by Andrey Valyaev on 27-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `41-96ac84d5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:dronmdf/telebot#81`.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#81` is not in scope.
