### ISSUE TITLE
reaction.py:2-6: Это мешок с данными. Но этот класс...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#85]
The puzzle `74-f3baff60` (from #74) in [`tb/sources/reaction.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/reaction.py) (lines 2-6) has to be resolved: "Это мешок с данными. Но этот класс может быть более ответственным за свои данные. В зависимости от того, какой сторедж - у экшина будет вызываться метод send, или метод save. В который будет передаваться интрефейс транспорта, или интерфейс БД соответственно."

The puzzle was created by Andrey Valyaev on 27-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#85` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+985](http://www.0crat.com/u/dronmdf).

**Comment by 0pdd** [comment]
The puzzle `74-f3baff60` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#85` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+1030](http://www.0crat.com/u/dronmdf).
