### ISSUE TITLE
Создать ReactionConcrete

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#87]
Эта реакция всегда будет на определенную фразу возвращать другую определенную фразу.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#87` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+1020](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+1020](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#87` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+1050](http://www.0crat.com/u/dronmdf).
