### ISSUE TITLE
Создать ReactionAlways

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#88]
Эта реакция на любую фразу отвечает одним и тем же.

**Comment by DronMDF** [comment]
@0crat assign @Michaelo0

**Comment by 0crat** [comment]
> @0crat assign @Michaelo0  ([here](https://github.com/DronMDF/telebot/issues/88#issuecomment-349075125))

@DronMDF Job `gh:dronmdf/telebot#88` assigned to @michaelo0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+1070](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+1070](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
@michaelo0 this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@michaelo0 this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#88` is now out of scope.
