### ISSUE TITLE
Создать реакцию, которая ограничивает доступ несанкционированных пользователей.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#89]
Эта реация должна из конфигурации подчитывать имя администратора, и передавать управление далее только для него.

**Comment by DronMDF** [comment]
Имя пользователя можно проверить так:
update.effective_user.username
Правда написано, что оно опциональное. Возможно не у всех установлено?

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#89` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+1060](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+1060](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
@dronmdf this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@dronmdf this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@dronmdf resigned from `gh:dronmdf/telebot#89`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#89` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#89` assigned to @michaelo0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @michaelo0, total is [+150](http://www.0crat.com/u/michaelo0).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#89` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+330](http://www.0crat.com/u/sminux).
